### ISSUE TITLE
[Bug]: Does not handle locals with dot as decimal point

### ISSUE THREAD

**Issue by Lybecker** [microsoft/carbon-aware-sdk#195]
### Contact Details

anlybeck@microsoft.com

### What happened?

When sending the geo location request with latitude and longitude the decimal is not forwarded to WattTime.  

### client

WebAPI (Default)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JenMadiedo** [comment]
GSF PR: https://github.com/Green-Software-Foundation/carbon-aware-sdk/pull/193

**Comment by esgraham** [comment]
Merged in GSF.
