### ISSUE TITLE
Remove dead code paths

### ISSUE THREAD

**Issue by gfmatthews** [microsoft/carbon-aware-sdk#212]
## User Story
In order to improve the maintainability and readability of the codebase, unused code paths need to be removed.

## Acceptance Criteria

- [ ] No regressions in existing code paths.
- [ ]  `CarbonAware.Config` namespace and corresponding files are removed.
- [ ] Unused interfaces in `CarbonAware.Interfaces` are removed.
- [ ] `CarbonAwareCore` is removed.
- [ ] `CarbonAware.Plugins.BasicJsonPlugin` project is removed.
- [ ] `CarbonAware.WebAPI/src/plugins` directory is removed.
- [ ] `CarbonAware.WebAPI/src/carbon-aware.json` config file is removed.

**Comment by esgraham** [comment]
Merged
