### ISSUE TITLE
[Bug]: ElectricityMapsDataSource fails with regional settings with comma as decimal separator

### ISSUE THREAD

**Issue by Lybecker** [microsoft/carbon-aware-sdk#227]
### Contact Details

anlybeck@microsoft.com

### What happened?

Running the CA-SDK with regional settings e.g. Danish that uses comma as decimal separator fails. The HTTP request to ElectricityMaps API urlencodes the comma to %2C

### client

WebAPI (Default)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gfmatthews** [comment]
Definitely should fix this. Approving for triage - whomever picks this up, please investigate a fix that would solve this globally (i.e. for any region, not just US English or Danish)

**Comment by pritipath** [comment]
Merged in GSF
